#http
services:
  client:
    image: ghcr.io/vimaster/mancala:latest
    ports:
      - "3012:5173"
    environment:
      - APP=client
      - VITE_DISCORD_CLIENT_ID=${VITE_DISCORD_CLIENT_ID}
      - VITE_SERVER_HOST=http://server:9000
  server:
    image: ghcr.io/vimaster/mancala:latest
    ports:
      - "3013:9000"
    environment:
      - APP=server
      - JWT_SECRET=${JWT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
